all:demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo09 demo10

demo01:demo01.cpp
	g++ -g -o demo01 demo01.cpp -I/project/public /project/public/_public.cpp

demo02:demo02.cpp
	g++ -g -o demo02 demo02.cpp -I/project/public /project/public/_public.cpp

demo03:demo03.cpp
	g++ -g -o demo03 demo03.cpp -I/project/public /project/public/_public.cpp

demo04:demo04.cpp
	g++ -g -o demo04 demo04.cpp -I/project/public /project/public/_public.cpp

demo05:demo05.cpp
	g++ -g -o demo05 demo05.cpp -I/project/public /project/public/_public.cpp

demo06:demo06.cpp
	g++ -g -o demo06 demo06.cpp -I/project/public /project/public/_public.cpp

demo07:demo07.cpp
	g++ -g -o demo07 demo07.cpp -I/project/public /project/public/_public.cpp

demo08:demo08.cpp
	g++ -g -o demo08 demo08.cpp -I/project/public /project/public/_public.cpp

demo09:demo09.cpp
	g++ -g -o demo09 demo09.cpp -I/project/public /project/public/_public.cpp

demo10:demo10.cpp
	g++ -g -o demo10 demo10.cpp -I/project/public /project/public/_public.cpp

clean:
	rm -f demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo09 demo10

